// Auto-generated
let project = new Project('world');

project.addSources('Sources');
project.addLibrary("/Users/dg/Blender/ArmorySDK/armory");
project.addLibrary("/Users/dg/Blender/ArmorySDK/iron");
project.addParameter('-dce full');
project.addParameter('armory.trait.WalkNavigation');
project.addParameter("--macro keep('armory.trait.WalkNavigation')");
project.addParameter('arm.MyTrait');
project.addParameter("--macro keep('arm.MyTrait')");
project.addParameter('armory.trait.SimpleRotateObject');
project.addParameter("--macro keep('armory.trait.SimpleRotateObject')");
project.addShaders("build_armory/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_armory/compiled/Assets/**", { notinlist: true });
project.addAssets("build_armory/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance_0.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance_1.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance_2.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance_3.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance_4.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance_5.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance_6.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/hosek/hosek_radiance_7.hdr", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("/Users/dg/Blender/ArmorySDK/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("textures/ConcreteStructuralDivots/ConcreteStructuralDivots_basecolor.png", { notinlist: true });
project.addAssets("textures/ConcreteStructuralDivots/ConcreteStructuralDivots_normal.png", { notinlist: true });
project.addDefine('arm_hosek');
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_audio');
project.addDefine('arm_published');
project.addDefine('arm_soundcompress');
project.addDefine('arm_skin');
project.addDefine('arm_particles');
project.addDefine('arm_loadscreen');
project.addDefine('arm_resizable');


resolve(project);
